version: '3.7'
services:
  app:
    container_name: students-api-graphql
    image: node:16 
    working_dir: /app
    volumes:
      - '.:/app'
    entrypoint:
      - /bin/bash
      - "-c" 
      - "/usr/local/bin/npm install --force && /usr/local/bin/npm run dev:server" 
    ports:
      - 4000:4000